<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Boot Reservierung</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
<meta name="boat-reservation/config/environment" content="%7B%22modulePrefix%22%3A%22boat-reservation%22%2C%22environment%22%3A%22production%22%2C%22rootURL%22%3A%22/%22%2C%22locationType%22%3A%22auto%22%2C%22EmberENV%22%3A%7B%22FEATURES%22%3A%7B%7D%2C%22EXTEND_PROTOTYPES%22%3A%7B%22Date%22%3Afalse%7D%7D%2C%22APP%22%3A%7B%22name%22%3A%22boat-reservation%22%2C%22version%22%3A%221.0.0+df54e635%22%7D%2C%22exportApplicationGlobal%22%3Afalse%7D" />

    <link integrity="" rel="stylesheet" href="/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css">
    <link integrity="" rel="stylesheet" href="/assets/boat-reservation-d41d8cd98f00b204e9800998ecf8427e.css">

    
  </head>
  <body>
    

    <script src="/assets/vendor-91842180ec7b330ba42d84666b1f8c58.js" integrity="sha256-P6sGHzjqrAi+az/0KW5j/P93tb6lw5VlunwO5N+wR5Y= sha512-OmKH43wg/nBbDIvIcrmzaTI5zO5U04+IAmehogQ0thGGdyVZtiRKWkTdqhT3dNPfR26byXOrIMstTA+zvGmLhg==" ></script>
    <script src="/assets/boat-reservation-ef54fec9a2e580ebb1c4e6b64a2f89e0.js" integrity="sha256-aN7xNjog0/ouuBZ2qYYIRTnPR2VTQYlklr7zgy+HqKQ= sha512-xXqyqWHopV1JqfAgCmTOAMfL4/CMUXBpZ2dKgWqQ9w0+xsGUo1vqdsZkOWa/xfmlUMk75wyw1yBT5DLgyikOqg==" ></script>

    
  </body>
</html>
